### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by ppaysant** [maxime1992/pizza-sync#52] opened 2017-12-08 15:18 UTC
**Steps to reproduce**:
* be unlogged
* load pizza-sync web page in your browser
* before login box appears, click on pizza (any one)

The pizza img appears, maximized, but never, never you will see the login box again. 
You need to reload to log.

**Comment by alagane** [comment] 2018-09-22 23:11
Hi, even with the mocks I can't reproduce it, the login always appears first.

**Comment by maxime1992** [comment] 2018-09-23 08:41
When @ppaysant found this bug I remember being able to reproduce it without any problem. Had to be quick to click on the picture but still, most of the time it'd do it.

Just gave another try and as @alagane pointed out, this problem is not here anymore.

I suspect it might have been fixed by this [huge refactor](https://github.com/maxime1992/pizza-sync/pull/62) where I've also done a bit of cleaning and improving :+1: 

Closing for now, feel free to reopen if someone can repro.

**Closed by maxime1992** 2018-09-23 08:41 UTC
